[workspace]
members = ["./"]

[package]
name = "taskline"
version = "0.4.0"
authors = ["Danil Akhtarov <d.akhtarov@tinkoff.ru>"]
edition = "2021"
description = "A simple distributed task queue for Rust"
repository = "https://github.com/daxartio/taskline"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
redis = { version = "0.23", features=["connection-manager", "tokio-comp"] }
serde = { version = "1.0.164", features = ["serde_derive"] }
serde_json = { version = "1.0.96" }

[dev-dependencies]
tokio = { version = "1.28.2", features = ["full"] }
