[workspace]
members = ["./"]

[package]
name = "taskline"
version = "0.6.0"
authors = ["Danil Akhtarov <daxartio@gmail.com>"]
description = "A simple distributed task queue for Rust"
repository = "https://github.com/daxartio/taskline"
keywords = ["redis", "queue", "task", "async", "distributed"]
categories = ["asynchronous", "web-programming"]
license = "MIT"
edition = "2021"
rust-version = "1.60"

[dependencies]
async-trait = "0.1.68"
redis = { version = "0.23", features=["connection-manager", "tokio-comp"] }
serde = { version = "1.0.164", features = ["serde_derive"] }
serde_json = { version = "1.0.96" }

[dev-dependencies]
tokio = { version = "1.28.2", features = ["full"] }
